# Generated by Django 2.2.6 on 2020-03-02 23:02

from django.db import migrations, models
import django.db.models.deletion
import phaseone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('enc_aes_key', models.BinaryField(max_length=16)),
                ('aes_nonce', models.BinaryField(max_length=16)),
                ('aes_mac_tag', models.BinaryField(max_length=16)),
                ('aes_ciphertext', models.BinaryField()),
                ('id', models.IntegerField(default=phaseone.models.mint_id, primary_key=True, serialize=False)),
                ('publishing_videos', models.BooleanField()),
                ('publishing_recordings', models.BooleanField()),
                ('publishing_quotes', models.BooleanField()),
                ('survey_started', models.DateTimeField(null=True)),
                ('survey_token', models.CharField(default=phaseone.models.mint_token, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_participant', models.CharField(max_length=50)),
                ('label_validated', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phaseone.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('technique', models.CharField(choices=[('N', 'No technique'), ('R', 'Rotate'), ('Z', 'Zoom')], default='N', max_length=1)),
                ('validation', models.CharField(choices=[('-', 'Unvalidated'), ('P', 'Reject: video shows PII'), ('I', 'Reject: video inappropriate'), ('C', 'Video is clean')], default='-', max_length=1)),
                ('in_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('out_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phaseone.Thing')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_aes_key', models.BinaryField(max_length=16)),
                ('aes_nonce', models.BinaryField(max_length=16)),
                ('aes_mac_tag', models.BinaryField(max_length=16)),
                ('aes_ciphertext', models.BinaryField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phaseone.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
