# Generated by Django 2.2.6 on 2019-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelledMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('media', models.FileField(upload_to='')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
