# Generated by Django 2.2.6 on 2019-12-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.IntegerField(default=3256, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('survey_started', models.DateTimeField(null=True)),
                ('survey_token', models.CharField(default='82G0Su4J0uiQZ072MsnWnA', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=128)),
                ('vision_light_perception', models.CharField(max_length=1)),
                ('vision_full_fov', models.BooleanField()),
                ('vision_reduced_fov', models.BooleanField()),
                ('vision_1to3', models.BooleanField()),
                ('vision_3to6', models.BooleanField()),
                ('vision_6tox', models.BooleanField()),
                ('vision_more', models.TextField()),
                ('accessibility_voiceover', models.BooleanField()),
                ('accessibility_zoom', models.BooleanField()),
                ('accessibility_magnifier', models.BooleanField()),
                ('accessibility_displayaccomodations', models.BooleanField()),
                ('accessibility_speech', models.BooleanField()),
                ('accessibility_largetext', models.BooleanField()),
                ('accessibility_boldtext', models.BooleanField()),
                ('accessibility_buttonshapes', models.BooleanField()),
                ('accessibility_reducetransparency', models.BooleanField()),
                ('accessibility_increasecontrast', models.BooleanField()),
                ('accessibility_reducemotion', models.BooleanField()),
                ('accessibility_siri', models.BooleanField()),
                ('accessibility_braille', models.BooleanField()),
                ('accessibility_more', models.TextField()),
                ('apps_taptapsee', models.BooleanField()),
                ('apps_bemyeyes', models.BooleanField()),
                ('apps_seeingai', models.BooleanField()),
                ('apps_envision', models.BooleanField()),
                ('apps_more', models.TextField()),
                ('camera_usage', models.CharField(max_length=1)),
                ('camera_photos', models.BooleanField()),
                ('camera_videos', models.BooleanField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.Participant')),
            ],
        ),
    ]
