# Generated by Django 2.2.6 on 2020-01-06 15:38

from django.db import migrations, models
import django.db.models.deletion
import pilot.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.IntegerField(default=pilot.models.mint_id, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('survey_started', models.DateTimeField(null=True)),
                ('survey_token', models.CharField(default=pilot.models.mint_token, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_aes_key', models.BinaryField(max_length=16)),
                ('aes_nonce', models.BinaryField(max_length=16)),
                ('aes_mac_tag', models.BinaryField(max_length=16)),
                ('aes_ciphertext', models.BinaryField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilot.Participant')),
            ],
        ),
    ]
