# Generated by Django 2.2.6 on 2020-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_participant_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='publishing_quotes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='publishing_recordings',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='publishing_videos',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
