# Generated by Django 2.2.6 on 2020-01-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_auto_20200117_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelledmedia',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pilot.Participant'),
            preserve_default=False,
        ),
    ]
