# Generated by Django 2.2.6 on 2020-02-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_labelledmedia_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelledmedia',
            name='validation',
            field=models.CharField(choices=[('-', 'Unvalidated'), ('P', 'Reject: video shows PII'), ('I', 'Reject: video inappropriate'), ('C', 'Video is clean')], default='-', max_length=1),
        ),
    ]
