# Generated by Django 2.2.6 on 2020-02-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0007_auto_20200207_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='validated',
        ),
    ]
