# Generated by Django 2.2.6 on 2020-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_remove_label_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelledmedia',
            name='in_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='labelledmedia',
            name='out_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
