# Generated by Django 2.2.6 on 2020-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phasetwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sha256',
            field=models.BinaryField(default=b'', max_length=32),
            preserve_default=False,
        ),
    ]
