# Generated by Django 2.2.6 on 2020-04-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phaseone.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phaseone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='publishing_quotes',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='publishing_recordings',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='publishing_videos',
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=phaseone.models.random_filename),
        ),
        migrations.AlterField(
            model_name='video',
            name='technique',
            field=models.CharField(choices=[('T', 'Train'), ('Z', 'Test: Zoom'), ('P', 'Test: Pan')], default='N', max_length=1),
        ),
    ]
