# Generated by Django 2.2.6 on 2020-05-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0002_auto_20200429_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phaseone.Participant'),
        ),
        migrations.AlterField(
            model_name='video',
            name='validation',
            field=models.CharField(choices=[('-', 'Unvalidated'), ('P', 'Reject: video shows PII'), ('I', 'Reject: video inappropriate'), ('M', 'Reject: video does not feature object'), ('C', 'Video is clean')], default='-', max_length=1),
        ),
    ]
