# Generated by Django 2.2.6 on 2020-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phasetwo', '0003_auto_20201006_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='charity_choice',
            field=models.CharField(default='', max_length=5),
        ),
    ]
