# Generated by Django 2.2.6 on 2020-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0004_auto_20200514_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='in_study',
            field=models.BooleanField(default=True),
        ),
    ]
