# Generated by Django 2.2.6 on 2020-05-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0005_participant_in_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='survey_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
