# Generated by Django 2.2.6 on 2020-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0009_auto_20200624_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionperiod',
            name='name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
